// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/entgen/predicate"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/entgen/usermodel"
)

// UserModelUpdate is the builder for updating UserModel entities.
type UserModelUpdate struct {
	config
	hooks    []Hook
	mutation *UserModelMutation
}

// Where appends a list predicates to the UserModelUpdate builder.
func (umu *UserModelUpdate) Where(ps ...predicate.UserModel) *UserModelUpdate {
	umu.mutation.Where(ps...)
	return umu
}

// SetName sets the "name" field.
func (umu *UserModelUpdate) SetName(s string) *UserModelUpdate {
	umu.mutation.SetName(s)
	return umu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (umu *UserModelUpdate) SetNillableName(s *string) *UserModelUpdate {
	if s != nil {
		umu.SetName(*s)
	}
	return umu
}

// SetUserName sets the "user_name" field.
func (umu *UserModelUpdate) SetUserName(s string) *UserModelUpdate {
	umu.mutation.SetUserName(s)
	return umu
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (umu *UserModelUpdate) SetNillableUserName(s *string) *UserModelUpdate {
	if s != nil {
		umu.SetUserName(*s)
	}
	return umu
}

// SetEmail sets the "email" field.
func (umu *UserModelUpdate) SetEmail(s string) *UserModelUpdate {
	umu.mutation.SetEmail(s)
	return umu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (umu *UserModelUpdate) SetNillableEmail(s *string) *UserModelUpdate {
	if s != nil {
		umu.SetEmail(*s)
	}
	return umu
}

// Mutation returns the UserModelMutation object of the builder.
func (umu *UserModelUpdate) Mutation() *UserModelMutation {
	return umu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (umu *UserModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, umu.sqlSave, umu.mutation, umu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (umu *UserModelUpdate) SaveX(ctx context.Context) int {
	affected, err := umu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (umu *UserModelUpdate) Exec(ctx context.Context) error {
	_, err := umu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umu *UserModelUpdate) ExecX(ctx context.Context) {
	if err := umu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (umu *UserModelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usermodel.Table, usermodel.Columns, sqlgraph.NewFieldSpec(usermodel.FieldID, field.TypeInt))
	if ps := umu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := umu.mutation.Name(); ok {
		_spec.SetField(usermodel.FieldName, field.TypeString, value)
	}
	if value, ok := umu.mutation.UserName(); ok {
		_spec.SetField(usermodel.FieldUserName, field.TypeString, value)
	}
	if value, ok := umu.mutation.Email(); ok {
		_spec.SetField(usermodel.FieldEmail, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, umu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	umu.mutation.done = true
	return n, nil
}

// UserModelUpdateOne is the builder for updating a single UserModel entity.
type UserModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserModelMutation
}

// SetName sets the "name" field.
func (umuo *UserModelUpdateOne) SetName(s string) *UserModelUpdateOne {
	umuo.mutation.SetName(s)
	return umuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (umuo *UserModelUpdateOne) SetNillableName(s *string) *UserModelUpdateOne {
	if s != nil {
		umuo.SetName(*s)
	}
	return umuo
}

// SetUserName sets the "user_name" field.
func (umuo *UserModelUpdateOne) SetUserName(s string) *UserModelUpdateOne {
	umuo.mutation.SetUserName(s)
	return umuo
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (umuo *UserModelUpdateOne) SetNillableUserName(s *string) *UserModelUpdateOne {
	if s != nil {
		umuo.SetUserName(*s)
	}
	return umuo
}

// SetEmail sets the "email" field.
func (umuo *UserModelUpdateOne) SetEmail(s string) *UserModelUpdateOne {
	umuo.mutation.SetEmail(s)
	return umuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (umuo *UserModelUpdateOne) SetNillableEmail(s *string) *UserModelUpdateOne {
	if s != nil {
		umuo.SetEmail(*s)
	}
	return umuo
}

// Mutation returns the UserModelMutation object of the builder.
func (umuo *UserModelUpdateOne) Mutation() *UserModelMutation {
	return umuo.mutation
}

// Where appends a list predicates to the UserModelUpdate builder.
func (umuo *UserModelUpdateOne) Where(ps ...predicate.UserModel) *UserModelUpdateOne {
	umuo.mutation.Where(ps...)
	return umuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (umuo *UserModelUpdateOne) Select(field string, fields ...string) *UserModelUpdateOne {
	umuo.fields = append([]string{field}, fields...)
	return umuo
}

// Save executes the query and returns the updated UserModel entity.
func (umuo *UserModelUpdateOne) Save(ctx context.Context) (*UserModel, error) {
	return withHooks(ctx, umuo.sqlSave, umuo.mutation, umuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (umuo *UserModelUpdateOne) SaveX(ctx context.Context) *UserModel {
	node, err := umuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (umuo *UserModelUpdateOne) Exec(ctx context.Context) error {
	_, err := umuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umuo *UserModelUpdateOne) ExecX(ctx context.Context) {
	if err := umuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (umuo *UserModelUpdateOne) sqlSave(ctx context.Context) (_node *UserModel, err error) {
	_spec := sqlgraph.NewUpdateSpec(usermodel.Table, usermodel.Columns, sqlgraph.NewFieldSpec(usermodel.FieldID, field.TypeInt))
	id, ok := umuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entgen: missing "UserModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := umuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermodel.FieldID)
		for _, f := range fields {
			if !usermodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
			}
			if f != usermodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := umuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := umuo.mutation.Name(); ok {
		_spec.SetField(usermodel.FieldName, field.TypeString, value)
	}
	if value, ok := umuo.mutation.UserName(); ok {
		_spec.SetField(usermodel.FieldUserName, field.TypeString, value)
	}
	if value, ok := umuo.mutation.Email(); ok {
		_spec.SetField(usermodel.FieldEmail, field.TypeString, value)
	}
	_node = &UserModel{config: umuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, umuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	umuo.mutation.done = true
	return _node, nil
}
