// Code generated by ent, DO NOT EDIT.

package followsmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// FollowerUserID applies equality check predicate on the "follower_user_id" field. It's identical to FollowerUserIDEQ.
func FollowerUserID(v int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldFollowerUserID, v))
}

// FolloweeUserID applies equality check predicate on the "followee_user_id" field. It's identical to FolloweeUserIDEQ.
func FolloweeUserID(v int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldFolloweeUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotNull(FieldUpdatedAt))
}

// FollowerUserIDEQ applies the EQ predicate on the "follower_user_id" field.
func FollowerUserIDEQ(v int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldFollowerUserID, v))
}

// FollowerUserIDNEQ applies the NEQ predicate on the "follower_user_id" field.
func FollowerUserIDNEQ(v int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNEQ(FieldFollowerUserID, v))
}

// FollowerUserIDIn applies the In predicate on the "follower_user_id" field.
func FollowerUserIDIn(vs ...int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIn(FieldFollowerUserID, vs...))
}

// FollowerUserIDNotIn applies the NotIn predicate on the "follower_user_id" field.
func FollowerUserIDNotIn(vs ...int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotIn(FieldFollowerUserID, vs...))
}

// FolloweeUserIDEQ applies the EQ predicate on the "followee_user_id" field.
func FolloweeUserIDEQ(v int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldEQ(FieldFolloweeUserID, v))
}

// FolloweeUserIDNEQ applies the NEQ predicate on the "followee_user_id" field.
func FolloweeUserIDNEQ(v int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNEQ(FieldFolloweeUserID, v))
}

// FolloweeUserIDIn applies the In predicate on the "followee_user_id" field.
func FolloweeUserIDIn(vs ...int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldIn(FieldFolloweeUserID, vs...))
}

// FolloweeUserIDNotIn applies the NotIn predicate on the "followee_user_id" field.
func FolloweeUserIDNotIn(vs ...int64) predicate.FollowsModel {
	return predicate.FollowsModel(sql.FieldNotIn(FieldFolloweeUserID, vs...))
}

// HasFollower applies the HasEdge predicate on the "follower" edge.
func HasFollower() predicate.FollowsModel {
	return predicate.FollowsModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FollowerTable, FollowerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFollowerWith applies the HasEdge predicate on the "follower" edge with a given conditions (other predicates).
func HasFollowerWith(preds ...predicate.UserModel) predicate.FollowsModel {
	return predicate.FollowsModel(func(s *sql.Selector) {
		step := newFollowerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFollowee applies the HasEdge predicate on the "followee" edge.
func HasFollowee() predicate.FollowsModel {
	return predicate.FollowsModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FolloweeTable, FolloweeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFolloweeWith applies the HasEdge predicate on the "followee" edge with a given conditions (other predicates).
func HasFolloweeWith(preds ...predicate.UserModel) predicate.FollowsModel {
	return predicate.FollowsModel(func(s *sql.Selector) {
		step := newFolloweeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FollowsModel) predicate.FollowsModel {
	return predicate.FollowsModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FollowsModel) predicate.FollowsModel {
	return predicate.FollowsModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FollowsModel) predicate.FollowsModel {
	return predicate.FollowsModel(sql.NotPredicates(p))
}
