// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	UserName         string `json:"userName"`
	FollowCount      int    `json:"followCount"`
	FollowerCount    int    `json:"followerCount"`
	SerfIntroduction string `json:"serfIntroduction"`
	ProfileImageURL  string `json:"profileImageUrl"`
	IsFollowing      bool   `json:"isFollowing"`
	IsMySelf         bool   `json:"isMySelf"`
}

type UserInput struct {
	Name             string `json:"name"`
	UserName         string `json:"userName"`
	SerfIntroduction string `json:"serfIntroduction"`
}
