// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/followsmodel"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/usermodel"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FollowsModel is the client for interacting with the FollowsModel builders.
	FollowsModel *FollowsModelClient
	// UserModel is the client for interacting with the UserModel builders.
	UserModel *UserModelClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FollowsModel = NewFollowsModelClient(c.config)
	c.UserModel = NewUserModelClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("entgen: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entgen: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		FollowsModel: NewFollowsModelClient(cfg),
		UserModel:    NewUserModelClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		FollowsModel: NewFollowsModelClient(cfg),
		UserModel:    NewUserModelClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FollowsModel.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.FollowsModel.Use(hooks...)
	c.UserModel.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.FollowsModel.Intercept(interceptors...)
	c.UserModel.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FollowsModelMutation:
		return c.FollowsModel.mutate(ctx, m)
	case *UserModelMutation:
		return c.UserModel.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("entgen: unknown mutation type %T", m)
	}
}

// FollowsModelClient is a client for the FollowsModel schema.
type FollowsModelClient struct {
	config
}

// NewFollowsModelClient returns a client for the FollowsModel from the given config.
func NewFollowsModelClient(c config) *FollowsModelClient {
	return &FollowsModelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `followsmodel.Hooks(f(g(h())))`.
func (c *FollowsModelClient) Use(hooks ...Hook) {
	c.hooks.FollowsModel = append(c.hooks.FollowsModel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `followsmodel.Intercept(f(g(h())))`.
func (c *FollowsModelClient) Intercept(interceptors ...Interceptor) {
	c.inters.FollowsModel = append(c.inters.FollowsModel, interceptors...)
}

// Create returns a builder for creating a FollowsModel entity.
func (c *FollowsModelClient) Create() *FollowsModelCreate {
	mutation := newFollowsModelMutation(c.config, OpCreate)
	return &FollowsModelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FollowsModel entities.
func (c *FollowsModelClient) CreateBulk(builders ...*FollowsModelCreate) *FollowsModelCreateBulk {
	return &FollowsModelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FollowsModelClient) MapCreateBulk(slice any, setFunc func(*FollowsModelCreate, int)) *FollowsModelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FollowsModelCreateBulk{err: fmt.Errorf("calling to FollowsModelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FollowsModelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FollowsModelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FollowsModel.
func (c *FollowsModelClient) Update() *FollowsModelUpdate {
	mutation := newFollowsModelMutation(c.config, OpUpdate)
	return &FollowsModelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FollowsModelClient) UpdateOne(fm *FollowsModel) *FollowsModelUpdateOne {
	mutation := newFollowsModelMutation(c.config, OpUpdateOne, withFollowsModel(fm))
	return &FollowsModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FollowsModelClient) UpdateOneID(id int) *FollowsModelUpdateOne {
	mutation := newFollowsModelMutation(c.config, OpUpdateOne, withFollowsModelID(id))
	return &FollowsModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FollowsModel.
func (c *FollowsModelClient) Delete() *FollowsModelDelete {
	mutation := newFollowsModelMutation(c.config, OpDelete)
	return &FollowsModelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FollowsModelClient) DeleteOne(fm *FollowsModel) *FollowsModelDeleteOne {
	return c.DeleteOneID(fm.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FollowsModelClient) DeleteOneID(id int) *FollowsModelDeleteOne {
	builder := c.Delete().Where(followsmodel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FollowsModelDeleteOne{builder}
}

// Query returns a query builder for FollowsModel.
func (c *FollowsModelClient) Query() *FollowsModelQuery {
	return &FollowsModelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFollowsModel},
		inters: c.Interceptors(),
	}
}

// Get returns a FollowsModel entity by its id.
func (c *FollowsModelClient) Get(ctx context.Context, id int) (*FollowsModel, error) {
	return c.Query().Where(followsmodel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FollowsModelClient) GetX(ctx context.Context, id int) *FollowsModel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFollower queries the follower edge of a FollowsModel.
func (c *FollowsModelClient) QueryFollower(fm *FollowsModel) *UserModelQuery {
	query := (&UserModelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := fm.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(followsmodel.Table, followsmodel.FieldID, id),
			sqlgraph.To(usermodel.Table, usermodel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, followsmodel.FollowerTable, followsmodel.FollowerColumn),
		)
		fromV = sqlgraph.Neighbors(fm.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFollowee queries the followee edge of a FollowsModel.
func (c *FollowsModelClient) QueryFollowee(fm *FollowsModel) *UserModelQuery {
	query := (&UserModelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := fm.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(followsmodel.Table, followsmodel.FieldID, id),
			sqlgraph.To(usermodel.Table, usermodel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, followsmodel.FolloweeTable, followsmodel.FolloweeColumn),
		)
		fromV = sqlgraph.Neighbors(fm.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FollowsModelClient) Hooks() []Hook {
	return c.hooks.FollowsModel
}

// Interceptors returns the client interceptors.
func (c *FollowsModelClient) Interceptors() []Interceptor {
	return c.inters.FollowsModel
}

func (c *FollowsModelClient) mutate(ctx context.Context, m *FollowsModelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FollowsModelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FollowsModelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FollowsModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FollowsModelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entgen: unknown FollowsModel mutation op: %q", m.Op())
	}
}

// UserModelClient is a client for the UserModel schema.
type UserModelClient struct {
	config
}

// NewUserModelClient returns a client for the UserModel from the given config.
func NewUserModelClient(c config) *UserModelClient {
	return &UserModelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usermodel.Hooks(f(g(h())))`.
func (c *UserModelClient) Use(hooks ...Hook) {
	c.hooks.UserModel = append(c.hooks.UserModel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usermodel.Intercept(f(g(h())))`.
func (c *UserModelClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserModel = append(c.inters.UserModel, interceptors...)
}

// Create returns a builder for creating a UserModel entity.
func (c *UserModelClient) Create() *UserModelCreate {
	mutation := newUserModelMutation(c.config, OpCreate)
	return &UserModelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserModel entities.
func (c *UserModelClient) CreateBulk(builders ...*UserModelCreate) *UserModelCreateBulk {
	return &UserModelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserModelClient) MapCreateBulk(slice any, setFunc func(*UserModelCreate, int)) *UserModelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserModelCreateBulk{err: fmt.Errorf("calling to UserModelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserModelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserModelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserModel.
func (c *UserModelClient) Update() *UserModelUpdate {
	mutation := newUserModelMutation(c.config, OpUpdate)
	return &UserModelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserModelClient) UpdateOne(um *UserModel) *UserModelUpdateOne {
	mutation := newUserModelMutation(c.config, OpUpdateOne, withUserModel(um))
	return &UserModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserModelClient) UpdateOneID(id int64) *UserModelUpdateOne {
	mutation := newUserModelMutation(c.config, OpUpdateOne, withUserModelID(id))
	return &UserModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserModel.
func (c *UserModelClient) Delete() *UserModelDelete {
	mutation := newUserModelMutation(c.config, OpDelete)
	return &UserModelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserModelClient) DeleteOne(um *UserModel) *UserModelDeleteOne {
	return c.DeleteOneID(um.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserModelClient) DeleteOneID(id int64) *UserModelDeleteOne {
	builder := c.Delete().Where(usermodel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserModelDeleteOne{builder}
}

// Query returns a query builder for UserModel.
func (c *UserModelClient) Query() *UserModelQuery {
	return &UserModelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserModel},
		inters: c.Interceptors(),
	}
}

// Get returns a UserModel entity by its id.
func (c *UserModelClient) Get(ctx context.Context, id int64) (*UserModel, error) {
	return c.Query().Where(usermodel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserModelClient) GetX(ctx context.Context, id int64) *UserModel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFollowers queries the followers edge of a UserModel.
func (c *UserModelClient) QueryFollowers(um *UserModel) *FollowsModelQuery {
	query := (&FollowsModelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := um.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usermodel.Table, usermodel.FieldID, id),
			sqlgraph.To(followsmodel.Table, followsmodel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, usermodel.FollowersTable, usermodel.FollowersColumn),
		)
		fromV = sqlgraph.Neighbors(um.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFollowees queries the followees edge of a UserModel.
func (c *UserModelClient) QueryFollowees(um *UserModel) *FollowsModelQuery {
	query := (&FollowsModelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := um.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usermodel.Table, usermodel.FieldID, id),
			sqlgraph.To(followsmodel.Table, followsmodel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, usermodel.FolloweesTable, usermodel.FolloweesColumn),
		)
		fromV = sqlgraph.Neighbors(um.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserModelClient) Hooks() []Hook {
	return c.hooks.UserModel
}

// Interceptors returns the client interceptors.
func (c *UserModelClient) Interceptors() []Interceptor {
	return c.inters.UserModel
}

func (c *UserModelClient) mutate(ctx context.Context, m *UserModelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserModelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserModelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserModelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserModelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("entgen: unknown UserModel mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		FollowsModel, UserModel []ent.Hook
	}
	inters struct {
		FollowsModel, UserModel []ent.Interceptor
	}
)
