// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/followsmodel"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/predicate"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/usermodel"
)

// FollowsModelQuery is the builder for querying FollowsModel entities.
type FollowsModelQuery struct {
	config
	ctx          *QueryContext
	order        []followsmodel.OrderOption
	inters       []Interceptor
	predicates   []predicate.FollowsModel
	withFollower *UserModelQuery
	withFollowee *UserModelQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FollowsModelQuery builder.
func (fmq *FollowsModelQuery) Where(ps ...predicate.FollowsModel) *FollowsModelQuery {
	fmq.predicates = append(fmq.predicates, ps...)
	return fmq
}

// Limit the number of records to be returned by this query.
func (fmq *FollowsModelQuery) Limit(limit int) *FollowsModelQuery {
	fmq.ctx.Limit = &limit
	return fmq
}

// Offset to start from.
func (fmq *FollowsModelQuery) Offset(offset int) *FollowsModelQuery {
	fmq.ctx.Offset = &offset
	return fmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fmq *FollowsModelQuery) Unique(unique bool) *FollowsModelQuery {
	fmq.ctx.Unique = &unique
	return fmq
}

// Order specifies how the records should be ordered.
func (fmq *FollowsModelQuery) Order(o ...followsmodel.OrderOption) *FollowsModelQuery {
	fmq.order = append(fmq.order, o...)
	return fmq
}

// QueryFollower chains the current query on the "follower" edge.
func (fmq *FollowsModelQuery) QueryFollower() *UserModelQuery {
	query := (&UserModelClient{config: fmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(followsmodel.Table, followsmodel.FieldID, selector),
			sqlgraph.To(usermodel.Table, usermodel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, followsmodel.FollowerTable, followsmodel.FollowerColumn),
		)
		fromU = sqlgraph.SetNeighbors(fmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFollowee chains the current query on the "followee" edge.
func (fmq *FollowsModelQuery) QueryFollowee() *UserModelQuery {
	query := (&UserModelClient{config: fmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(followsmodel.Table, followsmodel.FieldID, selector),
			sqlgraph.To(usermodel.Table, usermodel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, followsmodel.FolloweeTable, followsmodel.FolloweeColumn),
		)
		fromU = sqlgraph.SetNeighbors(fmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FollowsModel entity from the query.
// Returns a *NotFoundError when no FollowsModel was found.
func (fmq *FollowsModelQuery) First(ctx context.Context) (*FollowsModel, error) {
	nodes, err := fmq.Limit(1).All(setContextOp(ctx, fmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{followsmodel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fmq *FollowsModelQuery) FirstX(ctx context.Context) *FollowsModel {
	node, err := fmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FollowsModel ID from the query.
// Returns a *NotFoundError when no FollowsModel ID was found.
func (fmq *FollowsModelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fmq.Limit(1).IDs(setContextOp(ctx, fmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{followsmodel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fmq *FollowsModelQuery) FirstIDX(ctx context.Context) int {
	id, err := fmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FollowsModel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FollowsModel entity is found.
// Returns a *NotFoundError when no FollowsModel entities are found.
func (fmq *FollowsModelQuery) Only(ctx context.Context) (*FollowsModel, error) {
	nodes, err := fmq.Limit(2).All(setContextOp(ctx, fmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{followsmodel.Label}
	default:
		return nil, &NotSingularError{followsmodel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fmq *FollowsModelQuery) OnlyX(ctx context.Context) *FollowsModel {
	node, err := fmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FollowsModel ID in the query.
// Returns a *NotSingularError when more than one FollowsModel ID is found.
// Returns a *NotFoundError when no entities are found.
func (fmq *FollowsModelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fmq.Limit(2).IDs(setContextOp(ctx, fmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{followsmodel.Label}
	default:
		err = &NotSingularError{followsmodel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fmq *FollowsModelQuery) OnlyIDX(ctx context.Context) int {
	id, err := fmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FollowsModels.
func (fmq *FollowsModelQuery) All(ctx context.Context) ([]*FollowsModel, error) {
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryAll)
	if err := fmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FollowsModel, *FollowsModelQuery]()
	return withInterceptors[[]*FollowsModel](ctx, fmq, qr, fmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fmq *FollowsModelQuery) AllX(ctx context.Context) []*FollowsModel {
	nodes, err := fmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FollowsModel IDs.
func (fmq *FollowsModelQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fmq.ctx.Unique == nil && fmq.path != nil {
		fmq.Unique(true)
	}
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryIDs)
	if err = fmq.Select(followsmodel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fmq *FollowsModelQuery) IDsX(ctx context.Context) []int {
	ids, err := fmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fmq *FollowsModelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryCount)
	if err := fmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fmq, querierCount[*FollowsModelQuery](), fmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fmq *FollowsModelQuery) CountX(ctx context.Context) int {
	count, err := fmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fmq *FollowsModelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fmq.ctx, ent.OpQueryExist)
	switch _, err := fmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fmq *FollowsModelQuery) ExistX(ctx context.Context) bool {
	exist, err := fmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FollowsModelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fmq *FollowsModelQuery) Clone() *FollowsModelQuery {
	if fmq == nil {
		return nil
	}
	return &FollowsModelQuery{
		config:       fmq.config,
		ctx:          fmq.ctx.Clone(),
		order:        append([]followsmodel.OrderOption{}, fmq.order...),
		inters:       append([]Interceptor{}, fmq.inters...),
		predicates:   append([]predicate.FollowsModel{}, fmq.predicates...),
		withFollower: fmq.withFollower.Clone(),
		withFollowee: fmq.withFollowee.Clone(),
		// clone intermediate query.
		sql:  fmq.sql.Clone(),
		path: fmq.path,
	}
}

// WithFollower tells the query-builder to eager-load the nodes that are connected to
// the "follower" edge. The optional arguments are used to configure the query builder of the edge.
func (fmq *FollowsModelQuery) WithFollower(opts ...func(*UserModelQuery)) *FollowsModelQuery {
	query := (&UserModelClient{config: fmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fmq.withFollower = query
	return fmq
}

// WithFollowee tells the query-builder to eager-load the nodes that are connected to
// the "followee" edge. The optional arguments are used to configure the query builder of the edge.
func (fmq *FollowsModelQuery) WithFollowee(opts ...func(*UserModelQuery)) *FollowsModelQuery {
	query := (&UserModelClient{config: fmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fmq.withFollowee = query
	return fmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FollowsModel.Query().
//		GroupBy(followsmodel.FieldCreatedAt).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (fmq *FollowsModelQuery) GroupBy(field string, fields ...string) *FollowsModelGroupBy {
	fmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FollowsModelGroupBy{build: fmq}
	grbuild.flds = &fmq.ctx.Fields
	grbuild.label = followsmodel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FollowsModel.Query().
//		Select(followsmodel.FieldCreatedAt).
//		Scan(ctx, &v)
func (fmq *FollowsModelQuery) Select(fields ...string) *FollowsModelSelect {
	fmq.ctx.Fields = append(fmq.ctx.Fields, fields...)
	sbuild := &FollowsModelSelect{FollowsModelQuery: fmq}
	sbuild.label = followsmodel.Label
	sbuild.flds, sbuild.scan = &fmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FollowsModelSelect configured with the given aggregations.
func (fmq *FollowsModelQuery) Aggregate(fns ...AggregateFunc) *FollowsModelSelect {
	return fmq.Select().Aggregate(fns...)
}

func (fmq *FollowsModelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fmq.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fmq); err != nil {
				return err
			}
		}
	}
	for _, f := range fmq.ctx.Fields {
		if !followsmodel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if fmq.path != nil {
		prev, err := fmq.path(ctx)
		if err != nil {
			return err
		}
		fmq.sql = prev
	}
	return nil
}

func (fmq *FollowsModelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FollowsModel, error) {
	var (
		nodes       = []*FollowsModel{}
		_spec       = fmq.querySpec()
		loadedTypes = [2]bool{
			fmq.withFollower != nil,
			fmq.withFollowee != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FollowsModel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FollowsModel{config: fmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fmq.withFollower; query != nil {
		if err := fmq.loadFollower(ctx, query, nodes, nil,
			func(n *FollowsModel, e *UserModel) { n.Edges.Follower = e }); err != nil {
			return nil, err
		}
	}
	if query := fmq.withFollowee; query != nil {
		if err := fmq.loadFollowee(ctx, query, nodes, nil,
			func(n *FollowsModel, e *UserModel) { n.Edges.Followee = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fmq *FollowsModelQuery) loadFollower(ctx context.Context, query *UserModelQuery, nodes []*FollowsModel, init func(*FollowsModel), assign func(*FollowsModel, *UserModel)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FollowsModel)
	for i := range nodes {
		fk := nodes[i].FollowerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usermodel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "follower_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fmq *FollowsModelQuery) loadFollowee(ctx context.Context, query *UserModelQuery, nodes []*FollowsModel, init func(*FollowsModel), assign func(*FollowsModel, *UserModel)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FollowsModel)
	for i := range nodes {
		fk := nodes[i].FolloweeUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usermodel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "followee_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fmq *FollowsModelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fmq.querySpec()
	_spec.Node.Columns = fmq.ctx.Fields
	if len(fmq.ctx.Fields) > 0 {
		_spec.Unique = fmq.ctx.Unique != nil && *fmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fmq.driver, _spec)
}

func (fmq *FollowsModelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(followsmodel.Table, followsmodel.Columns, sqlgraph.NewFieldSpec(followsmodel.FieldID, field.TypeInt))
	_spec.From = fmq.sql
	if unique := fmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fmq.path != nil {
		_spec.Unique = true
	}
	if fields := fmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, followsmodel.FieldID)
		for i := range fields {
			if fields[i] != followsmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if fmq.withFollower != nil {
			_spec.Node.AddColumnOnce(followsmodel.FieldFollowerUserID)
		}
		if fmq.withFollowee != nil {
			_spec.Node.AddColumnOnce(followsmodel.FieldFolloweeUserID)
		}
	}
	if ps := fmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fmq *FollowsModelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fmq.driver.Dialect())
	t1 := builder.Table(followsmodel.Table)
	columns := fmq.ctx.Fields
	if len(columns) == 0 {
		columns = followsmodel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fmq.sql != nil {
		selector = fmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fmq.ctx.Unique != nil && *fmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fmq.predicates {
		p(selector)
	}
	for _, p := range fmq.order {
		p(selector)
	}
	if offset := fmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FollowsModelGroupBy is the group-by builder for FollowsModel entities.
type FollowsModelGroupBy struct {
	selector
	build *FollowsModelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fmgb *FollowsModelGroupBy) Aggregate(fns ...AggregateFunc) *FollowsModelGroupBy {
	fmgb.fns = append(fmgb.fns, fns...)
	return fmgb
}

// Scan applies the selector query and scans the result into the given value.
func (fmgb *FollowsModelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fmgb.build.ctx, ent.OpQueryGroupBy)
	if err := fmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowsModelQuery, *FollowsModelGroupBy](ctx, fmgb.build, fmgb, fmgb.build.inters, v)
}

func (fmgb *FollowsModelGroupBy) sqlScan(ctx context.Context, root *FollowsModelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fmgb.fns))
	for _, fn := range fmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fmgb.flds)+len(fmgb.fns))
		for _, f := range *fmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FollowsModelSelect is the builder for selecting fields of FollowsModel entities.
type FollowsModelSelect struct {
	*FollowsModelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fms *FollowsModelSelect) Aggregate(fns ...AggregateFunc) *FollowsModelSelect {
	fms.fns = append(fms.fns, fns...)
	return fms
}

// Scan applies the selector query and scans the result into the given value.
func (fms *FollowsModelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fms.ctx, ent.OpQuerySelect)
	if err := fms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowsModelQuery, *FollowsModelSelect](ctx, fms.FollowsModelQuery, fms, fms.inters, v)
}

func (fms *FollowsModelSelect) sqlScan(ctx context.Context, root *FollowsModelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fms.fns))
	for _, fn := range fms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
