// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/followsmodel"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/predicate"
)

// FollowsModelDelete is the builder for deleting a FollowsModel entity.
type FollowsModelDelete struct {
	config
	hooks    []Hook
	mutation *FollowsModelMutation
}

// Where appends a list predicates to the FollowsModelDelete builder.
func (fmd *FollowsModelDelete) Where(ps ...predicate.FollowsModel) *FollowsModelDelete {
	fmd.mutation.Where(ps...)
	return fmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fmd *FollowsModelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fmd.sqlExec, fmd.mutation, fmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fmd *FollowsModelDelete) ExecX(ctx context.Context) int {
	n, err := fmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fmd *FollowsModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(followsmodel.Table, sqlgraph.NewFieldSpec(followsmodel.FieldID, field.TypeInt))
	if ps := fmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fmd.mutation.done = true
	return affected, err
}

// FollowsModelDeleteOne is the builder for deleting a single FollowsModel entity.
type FollowsModelDeleteOne struct {
	fmd *FollowsModelDelete
}

// Where appends a list predicates to the FollowsModelDelete builder.
func (fmdo *FollowsModelDeleteOne) Where(ps ...predicate.FollowsModel) *FollowsModelDeleteOne {
	fmdo.fmd.mutation.Where(ps...)
	return fmdo
}

// Exec executes the deletion query.
func (fmdo *FollowsModelDeleteOne) Exec(ctx context.Context) error {
	n, err := fmdo.fmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{followsmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fmdo *FollowsModelDeleteOne) ExecX(ctx context.Context) {
	if err := fmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
