// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/usermodel"
	"github.com/t-yamakoshi/24-fresh-backend-v2/schema/db/ent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	usermodelMixin := ent.UserModel{}.Mixin()
	usermodelMixinFields0 := usermodelMixin[0].Fields()
	_ = usermodelMixinFields0
	usermodelFields := ent.UserModel{}.Fields()
	_ = usermodelFields
	// usermodelDescID is the schema descriptor for id field.
	usermodelDescID := usermodelMixinFields0[0].Descriptor()
	// usermodel.IDValidator is a validator for the "id" field. It is called by the builders before save.
	usermodel.IDValidator = usermodelDescID.Validators[0].(func(int64) error)
}
