// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/followsmodel"
	"github.com/t-yamakoshi/24-fresh-backend-v2/pkg/adapter/entgen/usermodel"
)

// UserModelCreate is the builder for creating a UserModel entity.
type UserModelCreate struct {
	config
	mutation *UserModelMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (umc *UserModelCreate) SetCreatedAt(t time.Time) *UserModelCreate {
	umc.mutation.SetCreatedAt(t)
	return umc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (umc *UserModelCreate) SetNillableCreatedAt(t *time.Time) *UserModelCreate {
	if t != nil {
		umc.SetCreatedAt(*t)
	}
	return umc
}

// SetUpdatedAt sets the "updated_at" field.
func (umc *UserModelCreate) SetUpdatedAt(t time.Time) *UserModelCreate {
	umc.mutation.SetUpdatedAt(t)
	return umc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (umc *UserModelCreate) SetNillableUpdatedAt(t *time.Time) *UserModelCreate {
	if t != nil {
		umc.SetUpdatedAt(*t)
	}
	return umc
}

// SetCognitoID sets the "cognito_id" field.
func (umc *UserModelCreate) SetCognitoID(s string) *UserModelCreate {
	umc.mutation.SetCognitoID(s)
	return umc
}

// SetName sets the "name" field.
func (umc *UserModelCreate) SetName(s string) *UserModelCreate {
	umc.mutation.SetName(s)
	return umc
}

// SetUserName sets the "user_name" field.
func (umc *UserModelCreate) SetUserName(s string) *UserModelCreate {
	umc.mutation.SetUserName(s)
	return umc
}

// SetBirthDate sets the "birth_date" field.
func (umc *UserModelCreate) SetBirthDate(t time.Time) *UserModelCreate {
	umc.mutation.SetBirthDate(t)
	return umc
}

// SetGender sets the "gender" field.
func (umc *UserModelCreate) SetGender(u usermodel.Gender) *UserModelCreate {
	umc.mutation.SetGender(u)
	return umc
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (umc *UserModelCreate) SetNillableGender(u *usermodel.Gender) *UserModelCreate {
	if u != nil {
		umc.SetGender(*u)
	}
	return umc
}

// SetSelfIntroduction sets the "self_introduction" field.
func (umc *UserModelCreate) SetSelfIntroduction(s string) *UserModelCreate {
	umc.mutation.SetSelfIntroduction(s)
	return umc
}

// SetNillableSelfIntroduction sets the "self_introduction" field if the given value is not nil.
func (umc *UserModelCreate) SetNillableSelfIntroduction(s *string) *UserModelCreate {
	if s != nil {
		umc.SetSelfIntroduction(*s)
	}
	return umc
}

// SetProfileImage sets the "profile_image" field.
func (umc *UserModelCreate) SetProfileImage(s string) *UserModelCreate {
	umc.mutation.SetProfileImage(s)
	return umc
}

// SetNillableProfileImage sets the "profile_image" field if the given value is not nil.
func (umc *UserModelCreate) SetNillableProfileImage(s *string) *UserModelCreate {
	if s != nil {
		umc.SetProfileImage(*s)
	}
	return umc
}

// SetEmail sets the "email" field.
func (umc *UserModelCreate) SetEmail(s string) *UserModelCreate {
	umc.mutation.SetEmail(s)
	return umc
}

// SetID sets the "id" field.
func (umc *UserModelCreate) SetID(i int64) *UserModelCreate {
	umc.mutation.SetID(i)
	return umc
}

// AddFollowerIDs adds the "followers" edge to the FollowsModel entity by IDs.
func (umc *UserModelCreate) AddFollowerIDs(ids ...int) *UserModelCreate {
	umc.mutation.AddFollowerIDs(ids...)
	return umc
}

// AddFollowers adds the "followers" edges to the FollowsModel entity.
func (umc *UserModelCreate) AddFollowers(f ...*FollowsModel) *UserModelCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return umc.AddFollowerIDs(ids...)
}

// AddFolloweeIDs adds the "followees" edge to the FollowsModel entity by IDs.
func (umc *UserModelCreate) AddFolloweeIDs(ids ...int) *UserModelCreate {
	umc.mutation.AddFolloweeIDs(ids...)
	return umc
}

// AddFollowees adds the "followees" edges to the FollowsModel entity.
func (umc *UserModelCreate) AddFollowees(f ...*FollowsModel) *UserModelCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return umc.AddFolloweeIDs(ids...)
}

// Mutation returns the UserModelMutation object of the builder.
func (umc *UserModelCreate) Mutation() *UserModelMutation {
	return umc.mutation
}

// Save creates the UserModel in the database.
func (umc *UserModelCreate) Save(ctx context.Context) (*UserModel, error) {
	return withHooks(ctx, umc.sqlSave, umc.mutation, umc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (umc *UserModelCreate) SaveX(ctx context.Context) *UserModel {
	v, err := umc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umc *UserModelCreate) Exec(ctx context.Context) error {
	_, err := umc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umc *UserModelCreate) ExecX(ctx context.Context) {
	if err := umc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (umc *UserModelCreate) check() error {
	if _, ok := umc.mutation.CognitoID(); !ok {
		return &ValidationError{Name: "cognito_id", err: errors.New(`entgen: missing required field "UserModel.cognito_id"`)}
	}
	if _, ok := umc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`entgen: missing required field "UserModel.name"`)}
	}
	if _, ok := umc.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`entgen: missing required field "UserModel.user_name"`)}
	}
	if _, ok := umc.mutation.BirthDate(); !ok {
		return &ValidationError{Name: "birth_date", err: errors.New(`entgen: missing required field "UserModel.birth_date"`)}
	}
	if v, ok := umc.mutation.Gender(); ok {
		if err := usermodel.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`entgen: validator failed for field "UserModel.gender": %w`, err)}
		}
	}
	if _, ok := umc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`entgen: missing required field "UserModel.email"`)}
	}
	if v, ok := umc.mutation.ID(); ok {
		if err := usermodel.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`entgen: validator failed for field "UserModel.id": %w`, err)}
		}
	}
	return nil
}

func (umc *UserModelCreate) sqlSave(ctx context.Context) (*UserModel, error) {
	if err := umc.check(); err != nil {
		return nil, err
	}
	_node, _spec := umc.createSpec()
	if err := sqlgraph.CreateNode(ctx, umc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	umc.mutation.id = &_node.ID
	umc.mutation.done = true
	return _node, nil
}

func (umc *UserModelCreate) createSpec() (*UserModel, *sqlgraph.CreateSpec) {
	var (
		_node = &UserModel{config: umc.config}
		_spec = sqlgraph.NewCreateSpec(usermodel.Table, sqlgraph.NewFieldSpec(usermodel.FieldID, field.TypeInt64))
	)
	if id, ok := umc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := umc.mutation.CreatedAt(); ok {
		_spec.SetField(usermodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := umc.mutation.UpdatedAt(); ok {
		_spec.SetField(usermodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := umc.mutation.CognitoID(); ok {
		_spec.SetField(usermodel.FieldCognitoID, field.TypeString, value)
		_node.CognitoID = value
	}
	if value, ok := umc.mutation.Name(); ok {
		_spec.SetField(usermodel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := umc.mutation.UserName(); ok {
		_spec.SetField(usermodel.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := umc.mutation.BirthDate(); ok {
		_spec.SetField(usermodel.FieldBirthDate, field.TypeTime, value)
		_node.BirthDate = value
	}
	if value, ok := umc.mutation.Gender(); ok {
		_spec.SetField(usermodel.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := umc.mutation.SelfIntroduction(); ok {
		_spec.SetField(usermodel.FieldSelfIntroduction, field.TypeString, value)
		_node.SelfIntroduction = value
	}
	if value, ok := umc.mutation.ProfileImage(); ok {
		_spec.SetField(usermodel.FieldProfileImage, field.TypeString, value)
		_node.ProfileImage = value
	}
	if value, ok := umc.mutation.Email(); ok {
		_spec.SetField(usermodel.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if nodes := umc.mutation.FollowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usermodel.FollowersTable,
			Columns: []string{usermodel.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(followsmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := umc.mutation.FolloweesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usermodel.FolloweesTable,
			Columns: []string{usermodel.FolloweesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(followsmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserModelCreateBulk is the builder for creating many UserModel entities in bulk.
type UserModelCreateBulk struct {
	config
	err      error
	builders []*UserModelCreate
}

// Save creates the UserModel entities in the database.
func (umcb *UserModelCreateBulk) Save(ctx context.Context) ([]*UserModel, error) {
	if umcb.err != nil {
		return nil, umcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(umcb.builders))
	nodes := make([]*UserModel, len(umcb.builders))
	mutators := make([]Mutator, len(umcb.builders))
	for i := range umcb.builders {
		func(i int, root context.Context) {
			builder := umcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, umcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, umcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, umcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (umcb *UserModelCreateBulk) SaveX(ctx context.Context) []*UserModel {
	v, err := umcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umcb *UserModelCreateBulk) Exec(ctx context.Context) error {
	_, err := umcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umcb *UserModelCreateBulk) ExecX(ctx context.Context) {
	if err := umcb.Exec(ctx); err != nil {
		panic(err)
	}
}
